//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput } from "@zenstackhq/runtime";
import type { SimplifiedModelResult as $SimplifiedModelResult, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/runtime";
export type TagFindManyArgs = $FindManyArgs<$Schema, "Tag">;
export type TagFindUniqueArgs = $FindUniqueArgs<$Schema, "Tag">;
export type TagFindFirstArgs = $FindFirstArgs<$Schema, "Tag">;
export type TagCreateArgs = $CreateArgs<$Schema, "Tag">;
export type TagCreateManyArgs = $CreateManyArgs<$Schema, "Tag">;
export type TagCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Tag">;
export type TagUpdateArgs = $UpdateArgs<$Schema, "Tag">;
export type TagUpdateManyArgs = $UpdateManyArgs<$Schema, "Tag">;
export type TagUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Tag">;
export type TagUpsertArgs = $UpsertArgs<$Schema, "Tag">;
export type TagDeleteArgs = $DeleteArgs<$Schema, "Tag">;
export type TagDeleteManyArgs = $DeleteManyArgs<$Schema, "Tag">;
export type TagCountArgs = $CountArgs<$Schema, "Tag">;
export type TagAggregateArgs = $AggregateArgs<$Schema, "Tag">;
export type TagGroupByArgs = $GroupByArgs<$Schema, "Tag">;
export type TagWhereInput = $WhereInput<$Schema, "Tag">;
export type TagSelect = $SelectInput<$Schema, "Tag">;
export type TagInclude = $IncludeInput<$Schema, "Tag">;
export type TagOmit = $OmitInput<$Schema, "Tag">;
export type TagGetPayload<Args extends $SelectIncludeOmit<$Schema, "Tag", true>> = $SimplifiedModelResult<$Schema, "Tag", Args>;
